language: cpp
dist: xenial
os:
- linux

branches:
  only:
  - master
  - /feat\/.*/
  - /test\/.*/
  - tmp

script: "mkdir -p build && cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=1 .. && make && make test"
